baseURL = "https://docs.lipobuddy.com/"
languageCode = "en-us"
title = "LiPo Buddy Documentation"
theme = "book"

[markup.goldmark.renderer]
  unsafe = true

disableKinds = ['taxonomy', 'taxonomyTerm']


[params]
  BookTheme = 'dark'